### ISSUE TITLE
Send command is enough and does not need key release

### ISSUE THREAD

**Issue by Slion** [Lakritzator/harmony#13]
Tested this through HarmonyDemo against SONOS PLAYBAR.
Sending simple command does not drive the volume all the way up or down.
There is apparently no need for sending key release.

**Comment by Lakritzator** [comment]
I know as I wrote somewhere I saw the same, but I don't trust it 😕 
There has to be a reason for the press/release.

I tried different status types, and I can confirm that press, release AND HOLD are accepted, some others I tried give an error.

Maybe I need to send press, hold, release for that effect.
Still, as the IOS Harmony App uses these press & release with a timestamp offset, I think we should leave it for now?

**Comment by Slion** [comment]
> I tried different status types, and I can confirm that press, release AND HOLD are accepted, some others I tried give an error.

Interesting, but still those are functions and not buttons. Any button on your remote can be assigned two functions. One function for quick press and release and one for press and hold. However that can not apply to the functions themselves. So I'm not sure exactly what that is. Maybe some kind of legacy stuff because the guy who initially design that system got it wrong.

**Comment by Slion** [comment]
> Still, as the IOS Harmony App uses these press & release with a timestamp offset, I think we should leave it for now?

We can leave it, it does not harm. I'm happy we have the simple sending of command too. Thus one can test and use which ever approach works best.
