### ISSUE TITLE
Publish NuGet package

### ISSUE THREAD

**Issue by Slion** [Lakritzator/harmony#14]
See: https://www.nuget.org/packages/SharpLibHarmony/
NuGet specs are on my fork you can pull it and update the authors field.
I'll be trying out that first version.

**Comment by Lakritzator** [comment]
I am confused, I already added a nuspec and created a package (just didn't publish it yet), what is different to this?

**Comment by Lakritzator** [comment]
https://github.com/Slion/harmony/blob/master/HarmonyHub/HarmonyHub.nuspec

**Comment by Slion** [comment]
Missed it :)

**Comment by Slion** [comment]
Well yours is designed to be used by the build server right?
Mine is published, needed to start using that stuff.

**Comment by Slion** [comment]
Done.
See: https://www.nuget.org/packages/SharpLibHarmony
