### ISSUE TITLE
Move all entities and other objects to HarmonyHub namespace

### ISSUE THREAD

**Issue by Slion** [Lakritzator/harmony#16]
It makes thing a lot easier and nicer to use in foreign projects where you don't want or just can't keep adding using directives because of various name conflict.

So HarmonyHub.Function is not such a pain as HarmonyHub.Entities.Response.Function.

**Comment by Lakritzator** [comment]
I moved them away to avoid the cluttering of the root... but I understand this request.
Let me think about it...

**Comment by Slion** [comment]
Which clutter are you talking about? There is like 2 classes in the HarmonyHub namespace.

**Comment by Lakritzator** [comment]
Yes, now there are, but there will be a lot if I move all to the root.

**Comment by Lakritzator** [comment]
Anyway, Howard has merged the PR, I currently don't want to push another so shortly.

**Comment by Slion** [comment]
We probably have less than twenty classes. That's not what I call clutter :)

**Comment by Slion** [comment]
Done.
