### ISSUE TITLE
How to get list of Activities 

### ISSUE THREAD

**Issue by damonbrodie** [Lakritzator/harmony#18]
Not really an issue, but not sure where to ask this.

The code works great - I can get a list of the devices and their buttons etc.  I can even start an activity if I know the number.  Is there an API call that this framework supplies that will output the list of activities and their associated IDs?

**Comment by damonbrodie** [comment]
Answered my own question:

Pasting this in case it helps others:

`            var harmonyConfig = await Program.Client.GetConfigAsync();
            PopulateTreeViewConfig(harmonyConfig);

            foreach (var activity in harmonyConfig.Activities)
            {
                listBoxActivities.Items.Add(activity.Label);
            }`

**Comment by Lakritzator** [comment]
Thanks for reporting and answering your own question.
I am sure this helps other too.
