### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by Lakritzator** [Lakritzator/harmony#6]
Make the result available in a nuget package

**Comment by Lakritzator** [comment]
Started work on this, although the nuspec is easy I also want to make sure the pdb is there and usefull so I am finishing (and forcing) the xml comments on the project.

@hdurdle If you are okay with all the changes we make, we need to be able to build & publish nuget packages. As I really dislike having those build on a user PC (viruses etc), I would like to know if you have a build-server like AppVeyor. If not, I suggest the following:
Create a team, move the repo over, than we need to see about rights but we should be able to build a AppVeyor job to create and publish.
We also need a nuget account, please create this, or use "mine" https://www.nuget.org/profiles/dapplo
or maybe @slion has one.

I do not need to be the maintainer, but to use the library I unfortunately have some standards 😄

**Comment by Lakritzator** [comment]
Oh, and you will need to decide on a license...

**Comment by Lakritzator** [comment]
I already added a AppVeyor.yml file which I used to build a demo package.

The demo nuget package(s) can be found here:
https://github.com/Lakritzator/harmony/releases

**Comment by Lakritzator** [comment]
@slion does that help?

**Comment by Lakritzator** [comment]
Closing for now, the basics are there.

**Comment by Slion** [comment]
Did you publish it already? I never used AppVeyor so you better manage that yourself.

**Comment by Lakritzator** [comment]
No, as I didn't want to publish something without clearing it with Howard.
I only published it as a release artifact to GitHub under releases.

What build server do you have?

**Comment by Slion** [comment]
Don't have any. Usually doing that myself for such small projects. I'm not worried about the publishing. @i8beef did publish his fork on NuGet.

**Comment by Lakritzator** [comment]
I prefer not to publish anything from my PC, if something gets infected I will get a sh*t storm.
Greenshot has about 30.000 downloads a week... just imagine I build this on my PC, which gets infected without knowing :astonished: 

I can imagine Howard doesn't have any either, and no NuGet account either, which is okay...
As AppVeyor needs access to the project (readonly but I need team access to it) Howard can place his repo in a Github Team and give read access to me. This way he has control an can revoke it any time, while AppVeyor takes care or building and publishing.

P.S.
If he wants to do it manually, that is his choice too...
By the time I build my app, and it's usable for the public, I can always create my own fork.
